### ISSUE TITLE
Provide support for b3c tracing headers

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#1674]
```yaml
management:
  tracing:
    propagation:
      consume: [B3,B3_MULTI,W3C]
      produce: [W3C]
```
